name: Build Release

on:
  push:
    tags:
      - "v*.*"

jobs:
  build-all:
    uses: ./.github/workflows/build-all.yml
    secrets: inherit
  create-release:
    runs-on: ubuntu-latest
    needs: build-all
    steps:
      - name: Downloading artifacts
        uses: actions/download-artifact@v4

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: '**/*.@(jar|apk|dmg|msi|AppImage)'
