name: Main Test Checks

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo 0
      - run: echo 1
      - run: echo "${{toJSON(github)}}"
      - run: printenv
