name: Markdown test

on:
  workflow_dispatch:
  pull_request:
    branches: [ test_action ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Unit tests
        if: always()
        id: custom-app-tests
        run: ./gradlew testUnitTest --stacktrace

      - name: Send PR status to Slack
        if: always()
        env:
          GIT: ${{ toJson(github) }}
          OUTCOMES: ${{ toJson(steps) }}
          SECRETS: ${{ toJson(secrets) }}
        run: ./gradlew -p .github/scripts/ postCheckResultsToSlack
